### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [dave080373/splurty-app#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by dave080373** [comment]
Hey Ken,
  Thanks for the positive words in your email.  I think I took care of your request, check it out and let me know.  I definitely see a difference when testing on my iPhone before and after my change. New code commit on GitHub is also added to Heroku so you can take a look via my prod envirement.

**Comment by dave080373** [comment]
👍🏻Thanks for the pointers!!!
